window.articlesData = [
  {
    date: "2026",
    title:
      "Advancing Safe and Responsible AI Adoption in Community Pharmacy Practice",
    authors: "",
    journal: "Leslie Dan Faculty of Pharmacy",
    course: "Network for Improving Health Systems",
    url: "",
    image: "Images/Leslie Dan NIHS Talk Panel.jpg",
    imageWidth: 1600,
    imageHeight: 1066,
    tag: ["Panel"],
  },
  {
    date: "2026",
    title: "AI in the Modern Workforce",
    authors: "",
    journal: "Bausch Health",
    url: "",
    image: "Images/bausch health speaking.jpg",
    tag: ["Industry Talk"],
  },
  {
    date: "2024",
    title: "Entrepreneurship",
    authors: "",
    journal: "PHM327 | University of Toronto",
    course: "Pharmacy Management, Leadership, and Entrepreneurship",
    url: "",
    image: "Images/entrepreneurshiplecture.jpg",
    tag: ["Academic Teaching"],
  },
  {
    date: "2025",
    title: "Artificial Intelligence, e-Therapies and Virtual Care",
    authors: "David Graztner, MD & Dr. Marlon Danilewitz, MD",
    journal: "Canadian Psychiatric Association",
    course: "75th Annual Conference",
    url: "",
    image: "Images/CPAspeaking.jpg",
    tag: ["Industry Talk"],
  },
  {
    date: "2023",
    title:
      "Harnessing the Power of Communication and Storytelling for Business Growth",
    authors: "",
    journal: "Healthcare Businesswomen's Association",
    url: "",
    image: "Images/HBA Speaking.jpg",
    tag: ["Panel"],
  },
  {
    date: "2024 - 2024",
    title: "AI in the Pharmaceutical Industry",
    authors: "",
    journal: "BTC2030 | University of Toronto",
    course: "Management of Technological Innovation",
    url: "",
    image: "Images/AI and Pharma.jpg",
    tag: ["Academic Teaching"],
  },
  {
    date: "2024 - 2024",
    title: "The AI Revolution in Healthcare",
    authors: "",
    journal: "Leslie Dan Faculty of Pharmacy",
    url: "",
    image: "Images/Speaking LDFP.jpg",
    course: "Pharmacy Changemakers",
    tag: ["Panel"],
  },
  {
    date: "2024 - 2024",
    title: "COVID-19 Vaccine Update",
    authors: "",
    journal: "British Columbia Pharmacy Association",
    url: "",
    image: "Images/covid19.jpg",
    tag: ["Industry Talk"],
  },
  {
    date: "2024 - 2024",
    title: "3D Printing Face Shields",
    authors: "",
    journal: "CAPSI Professional Development Week",
    url: "",
    image: "Images/capsi3dprinting.jpg",

    tag: ["Industry Talk"],
  },
  {
    date: "2024 - 2024",
    title: "Designing & Evaluating Impact",
    authors:
      "Collaborators: Jason M. Lo Hog Tian, Aisha Shafaqat, and Safaa Yaseen",
    journal: "The AFS Youth Assembly",
    url: "",
    image: "Images/AFS.jpeg",
    tag: ["Industry Talk"],
  },
  {
    date: "2023 - 2025",
    title: "Change Management",
    authors: "",
    journal: "PHM310 | University of Toronto",
    course: "Pharmacy in the Modern Health Care System",
    url: "",
    image: "Images/changemanagement.jpeg",
    tag: ["Academic Teaching"],
  },
  {
    date: "2022 - 2026",
    title: "Introduction to Financial Literacy",
    authors: "",
    journal: "PHM215 | University of Toronto",
    course: "Management: Skills, Communication & Collaboration",
    url: "",
    image: "Images/financelecture.jpg",
    tag: ["Academic Teaching"],
  },
  {
    date: "2025",
    title: "Power & Leadership",
    authors: "Collaborator: Peter Harbin",
    journal: "PHM215 | University of Toronto",
    course: "Management: Skills, Communication & Collaboration",
    url: "",
    image: "Images/powerinfluence.jpg",
    tag: ["Academic Teaching"],
  },
  {
    date: "2022 - 2026",
    title: "Business Planning",
    authors: "Collaborator: Karen Meagher",
    journal: "PHM215 | University of Toronto",
    course: "Management: Skills, Communication & Collaboration",
    url: "",
    image: "Images/businessplanimage.jpg",
    tag: ["Academic Teaching"],
  },
  {
    date: "2021 - 2026",
    title: "Microbiology in the Clinical Setting",
    authors: "",
    journal: "HMB312 | University of Toronto",
    course: "Laboratory in Health and Disease",
    url: "",
    image: "Images/clinicalmicrobiology.jpg",
    tag: ["Academic Teaching"],
  },
  {
    date: "2018 - 2023",
    title: "Antimicrobial Stewardship",
    authors: "",
    journal: "NEW116 | University of Toronto",
    course: "Science and Global Threats",
    coverText: "Resistance & Sensitivity",
    url: "",
    image: "Images/Writingcover.jpg",
    tag: ["Academic Teaching"],
  },
  {
    date: "2017 - 2023",
    title: "Vaccinations and Autism",
    authors: "",
    journal: "NEW106 | University of Toronto",
    course: "Science, Health and Social Justice",
    coverText: "An Intersection of Society & Science",
    url: "",
    image: "Images/Writingcover.jpg",
    tag: ["Academic Teaching"],
  },
];
